version: '3.8'
services:
  db:
    container_name: MutterCorp
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=MutterCorp
      - POSTGRES_PASSWORD=ma128sio4
      - POSTGRES_DB=MutterCorp
      - POSTGRES_HOST=localhost
      - POSTGRS_INITDB_ARGS=--locale=en_US.UTF-8
    ports:
      - 5932:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.0-alpine
    ports:
      - 6379:6379

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db-data:
