name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker build -t myapp .
          docker run myapp npm test

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success('build_and_test')

    steps:
      - name: Deploy to Production
        run: |
          # Add your production deployment steps here
          # For example, push the Docker image
